name: Lint

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

jobs:
  php:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1']

    name: php${{ matrix.php-versions }} lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up php${{ matrix.php-versions }}
        uses: shivammathur/setup-php@2.24.0
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
      - name: Lint
        run: composer run lint

  php-cs-fixer:
    name: php-cs check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up php
      uses: shivammathur/setup-php@2.24.0
      with:
        php-version: 7.4
        coverage: none
    - name: Install dependencies
      run: composer i
    - name: Run coding standards check
      run: composer run cs:check

  node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up npm7
        run: npm i -g npm@7
      - name: Install dependencies
        run: npm ci
      - name: ESLint
        run: npm run lint

  stylelint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    name: stylelint node${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up npm7
        run: npm i -g npm@7

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run stylelint
